/**
 * Generated API types — DO NOT EDIT BY HAND.
 *
 * This file is regenerated by `npm run generate` (in this package) from
 * `backend/openapi.json`. CI fails if the committed version is out of
 * date relative to the backend's current OpenAPI output.
 *
 * Until the first backend endpoint ships, this file declares a sentinel
 * type so the frontend can already import from `@unitor/api-types`
 * without errors.
 */

export type paths = Record<string, never>;
export type components = Record<string, never>;
export type operations = Record<string, never>;

export {};
